### ISSUE TITLE
Connector crashes when trying to get foreign amount

### ISSUE THREAD

**Issue by AmineI** [dvankley/firefly-plaid-connector-2#71] opened 2024-02-26 17:09 UTC
Hi,
Connector crashes if there is a Firefly transaction with a foreign amount in firefly. I'll be sending a quick PR

**Comment by dvankley** [comment] 2024-02-26 18:26
The change you reference here reverts [a change](https://github.com/dvankley/firefly-plaid-connector-2/commit/08fac2bfcf6f201ddef912f42239c6730f210fc7) I made recently to fix [an issue](https://github.com/dvankley/firefly-plaid-connector-2/issues/59) caused by changes in Firefly.

What version of Firefly and the connector are you running?

**Comment by dvankley** [comment] 2024-03-02 02:43
I tried to reproduce following your steps and didn't see any errors. Can you post an error log?

**Comment by dvankley** [comment] 2024-03-07 17:59
Ah, I see, it's crapping out on the floating point conversion to integer. Derp.
Knowing that and upon further reflection, I'm going to say let's go ahead and merge your original PR. It fixes the problem (as you said) and the actual value of my change https://github.com/dvankley/firefly-plaid-connector-2/commit/08fac2bfcf6f201ddef912f42239c6730f210fc7 was removing the obsolete `"0"` literals, not the `String`->`Int` type changes.
 I would like for currency amounts to be represented in the connector with a more suitable data type, but that's a larger undertaking that doesn't seem worth the trouble right now.

**Comment by dvankley** [comment] 2024-03-07 18:00
I'll cut a new release soonish after I merge in dependabot updates and do my basic regression tests.

**Comment by dvankley** [comment] 2024-03-08 01:02
Should be fixed in https://github.com/dvankley/firefly-plaid-connector-2/releases/tag/v1.1.1

**Closed** 2024-03-11 13:13 UTC
Labels: bug
